version: 0.2

phases:
  install:
    commands:
      - aws s3 ls
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $CODEBUILD_SOURCE_REPO_URL
      - echo $CODEBUILD_SOURCE_VERSION
      - echo "$CODEBUILD_WEBHOOK_TRIGGER" | sed 's|.*/||'
